#macro size 64 //Size of the squares

//Autogenerated maps
#macro pathLengthMultiplier 1
#macro pathLengthBase 50

//Pad controller
#macro padX 20 + spriteW(spr_dpad_0)/2
#macro padY room_height - 20 - spriteH(spr_dpad_0)/2
#macro inputReadDelay 6
//instanceCreate(oPad, padX, padY, "Interface");


//Read the last level played
ini_open("GameSettings.ini");
ini_write_real("game", "lastPlayedLevel", global.LEVEL);
ini_close();


//Choose a random sprite for the snake at the begginning of the game
snakeSprite = choose(sSnake, sSnake2, sSnake3,  sSnake4);
eggSprite = choose(sEgg, sEgg2, sEgg3, sEgg4);


initTable(); 


//Initial position of the snake in the table
iCurrent = 10;
jCurrent = 9;


//Autogenerated maps
pathLengthCurrent = 0;
iterations = 0;
path = 0;

var autoGeneratedMap = false;
if (autoGeneratedMap) {
	var pathLength = global.LEVEL*pathLengthMultiplier + pathLengthBase;
	random_set_seed(getSeed());
	destroyBlocRecursive(iCurrent, jCurrent, pathLength, "up");
}


//Create the snaake at the initial position and the initial movable positions
var obj = createInTable(iCurrent, jCurrent, oElement, snakeSprite);
obj.direction = 90;
obj.image_angle = 90;
createInTableMovables(iCurrent, jCurrent);


global.PAUSE = false;
time = 0;


fillWithCoins();


show_debug_message(path);