#macro size 64
#macro pathLengthMultiplier 1
#macro pathLengthBase 50

#macro padX 20 + spriteW(spr_dpad_0)/2
#macro padY room_height - 20 - spriteH(spr_dpad_0)/2
#macro inputReadDelay 6

ini_open("GameSettings.ini");
ini_write_real("game", "lastPlayedLevel", global.LEVEL);
ini_close();

//instanceCreate(oPad, padX, padY, "Interface");

table = 0;
initTable(); 

iCurrent = 10;
jCurrent = 9;

pathLengthCurrent = 0;
iterations = 0;
path = 0;

var autoGeneratedMap = false;
if (autoGeneratedMap) {
	var pathLength = global.LEVEL*pathLengthMultiplier + pathLengthBase;
	random_set_seed(getSeed());
	destroyBlocRecursive(iCurrent, jCurrent, pathLength, "up");
}

var obj = createInTable(iCurrent, jCurrent, oElement, sSnake);
obj.direction = 90;
obj.image_angle = 90;
createInTableMovables(iCurrent, jCurrent);

global.PAUSE = false;
time = 0;

show_debug_message(path);

fillWithCoins();